# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[main]]
  name = "Blog"
  pageRef = "posts"
  weight = 10

#[[main]]
#  name = "Archiv3e"
#  pageRef = "archive"
#  weight = 11

[[main]]
   name = "Archive"
   pageRef = "/archive/"
   weight = 20
[[main]]
  name = "LED"
  parent = "Archive"
  pageRef = "/categories/led/"
  weight = 21

[[main]]
  name = "Candles"
  parent = "Archive"
  pageRef = "/categories/candles/"
  weight = 22

[[main]]
  name = "Computer Architecture"
  parent = "Archive"
  pageRef = "/categories/computer-architecture/"
  weight = 23

[[main]]
  name = "Discrete Logic"
  parent = "Archive"
  pageRef = "/categories/discrete-logic/"
  weight = 24

[[main]]
  name = "Microcontroller"
  parent = "Archive"
  pageRef = "/categories/microcontroller/"
  weight = 25

[[main]]
  name = "ML & AI"
  parent = "Archive"
  pageRef = "/categories/ml--ai/"
  weight = 26

[[main]]
  name = "Reverse Engineering"
  parent = "Archive"
  pageRef = "/categories/reverse-engineering/"
  weight = 27

[[main]]
  name = "Science"
  parent = "Archive"
  pageRef = "/categories/science/"
  weight = 28

[[main]]
  pre = "github"
  name = ""
  url = "https://github.com/cpldcpu/"
  weight = 30

#[[main]]
#  name = "Parent"
#  weight = 20

#[[main]]
#  name = "example sub-menu 1"
#  parent = "Parent"
#  pageRef = "posts"
#  weight = 20

#[[main]]
#  name = "example sub-menu 2"
#  parent = "Parent"
#  pageRef = "posts"
#  weight = 20

#[[subnavigation]]
#  name = "An interesting topic"
#  pageRef = "tags/interesting-topic"
#  weight = 10

#[[subnavigation]]
#  name = "My Awesome Category"
#  pre = "github"
#  pageRef = "categories/awesome"
#  weight = 20

#[[main]]
#  name = "Categories"
#  pageRef = "categories"
#  weight = 20

#[[main]]
#  name = "Tags"
#  pageRef = "tags"
#  weight = 30


# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.


# [[footer]]
#   name = "Tags"
#   pageRef = "tags"
#   weight = 10

# [[footer]]
#   name = "Categories"
#   pageRef = "categories"
#   weight = 20
